# Generated by Django 2.0.13 on 2019-08-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoIntencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Ação', 'Ação'), ('Intenção', 'Intenção')], default='Ação', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PartesHistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='ordem do elemento na história')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_chatbot.AcaoIntencao')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_chatbot.Historia')),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('id_acao_intencao', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app_chatbot.AcaoIntencao')),
            ],
        ),
    ]
