# Generated by Django 2.0.13 on 2019-09-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parteshistoria',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.Historia'),
        ),
        migrations.AlterField(
            model_name='texto',
            name='id_acao_intencao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.AcaoIntencao'),
        ),
    ]
